Traceback (most recent call last):
  File "../exps/si_test.py", line 39, in <module>
    lr = [.03, .01][int(task_id / 5)]
IndexError: list index out of range
