2019-07-29 02:04:21.777600: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-07-29 02:04:22.141738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:85:00.0
totalMemory: 11.92GiB freeMemory: 11.84GiB
2019-07-29 02:04:22.141934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-07-29 02:04:29.879404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-29 02:04:29.879626: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-07-29 02:04:29.879777: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-07-29 02:04:29.881594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11477 MB memory) -> physical GPU (device: 0, name: Tesla K40c, pci bus id: 0000:85:00.0, compute capability: 3.5)
/clusterFS/home/student/kopp13/miniconda3/envs/tensorflow/lib/python3.5/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/clusterFS/home/student/kopp13/miniconda3/envs/tensorflow/lib/python3.5/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "../exps/mter_test.py", line 165, in <module>
    save_to_file(result_dicts, result_config['path'])
  File "../src/data/t_metrics.py", line 21, in save_to_file
    np.save(path + '_' + process_key + '_' + metric_key, metrics[metric_key])
  File "/clusterFS/home/student/kopp13/miniconda3/envs/tensorflow/lib/python3.5/site-packages/numpy/lib/npyio.py", line 524, in save
    fid.close()
OSError: [Errno 5] Input/output error
