2019-03-24 13:56:45.265322: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2019-03-24 13:56:45.494075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: GeForce GTX 960 major: 5 minor: 2 memoryClockRate(GHz): 1.2405
pciBusID: 0000:07:00.0
totalMemory: 3.95GiB freeMemory: 3.90GiB
2019-03-24 13:56:45.494192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:07:00.0, compute capability: 5.2)
2019-03-24 13:58:37.779253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 960, pci bus id: 0000:07:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "../exps/tter_test.py", line 147, in <module>
    save_to_file(result_dicts, result_config['path'])
  File "../src/data/t_metrics.py", line 21, in save_to_file
    np.save(path + '_' + process_key + '_' + metric_key, metrics[metric_key])
  File "/clusterFS/home/student/kopp13/miniconda3/envs/tensorflow/lib/python3.5/site-packages/numpy/lib/npyio.py", line 492, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '../nr/exp_7_te_s_m_loss.npy'
